# Generated by Django 5.2.4 on 2025-07-29 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kampanii')),
                ('message_content', models.TextField(verbose_name='Treść wiadomości')),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email i SMS')], max_length=10, verbose_name='Typ wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('excel_columns', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('sent', 'Wysłane'), ('failed', 'Błąd'), ('skipped', 'Pominięte')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sender.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'email', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=5)),
                ('final_message', models.TextField()),
                ('success', models.BooleanField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='sender.recipient')),
            ],
        ),
    ]
